### PR TITLE
Make specific access on dev environment optional

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Why? Because as you now have only one front controller, it is *always* deployed in production :)

By default, this part should be now disabled and let advanced users write every custom action they need to do instead of force every Symfony developer to remove this damn piece of code every time on every project.

And don't tell me it's insecure: it's really hard to make ``APP_DEBUG`` env variable in production by mistake 👍

### CODE REVIEW

**Comment by dunglas** [comment]
It is not straightforward for newcomers. You cannot start coding without Uncommenting those lines...
Usually you will not use this Docker compose file to deploy in production. APP_DEBUG will not be set until you do it explicitly, this code will not be executed.

**Comment by mickaelandrieu** [comment]
> . You cannot start coding without Uncommenting those lines...

Why? It's quite the opposite! Most of the time, even if you have exported `APP_DEBUG` you still can't access your dev environment :/

**Comment by dunglas** [comment]
It works on Linux and Mac but it seems to not work as expected on Windows.

**Comment by dunglas** [comment]
Can you just update this PR to remove this block totally as I've done in the framework bundle's recipe?

Thanks Mickaël!

**Comment by mickaelandrieu** [comment]
Yes Kevin, I'll do it probably tonight :)

Mickaël

**Comment by mickaelandrieu** [comment]
Done (sorry for the delay) and thank you to have done it at Symfony's level :)

**Comment by dunglas** [comment]
In fact, you can just remove the `web` directory now that this patch is in Flex!

**Comment by mickaelandrieu** [comment]
Yeah, I wanted to ask you why we keep the web folder :D I do it now sir :)

**Comment by dunglas** [comment]
> I don't know well Flex, will it create a new web folder for us?

Yes it will. No problem for this line.

**Comment by dunglas** [comment]
Thanks @mickaelandrieu!

**Pull request merged**
